In [5]:
dir = ""
if dir:
    print("Yes")
else:
    print("No")

No


In [6]:
(64, 64) + (3, )

(64, 64, 3)

In [14]:
import numpy as np
import torch
from torch import tensor
from torch import distributions as torchd

In [15]:
n_a = np.array([1, 2, 3])
torch.Tensor(n_a)[None]

tensor([[1., 2., 3.]])

In [25]:
uni = torchd.uniform.Uniform(torch.Tensor(-1 * np.ones(6))[None],
                                       torch.Tensor(np.ones(6))[None])

In [26]:
uni.batch_shape

torch.Size([1, 6])

In [27]:
uni.event_shape

torch.Size([])

In [34]:
uni.sample((6,))

tensor([[[ 0.7373, -0.7712, -0.8968,  0.5194,  0.5553,  0.1233]],

        [[ 0.4967,  0.1407,  0.7963, -0.9938,  0.0392,  0.9445]],

        [[-0.1944,  0.2913,  0.7074,  0.1775,  0.3793,  0.1960]],

        [[-0.9051,  0.4778,  0.9034,  0.2110, -0.7862, -0.8198]],

        [[-0.1389,  0.9077,  0.8655, -0.2884,  0.1689, -0.8523]],

        [[-0.4035,  0.3181,  0.1107,  0.1982, -0.7705, -0.2369]]])

In [35]:
uni.sample()

tensor([[ 0.5236,  0.7819, -0.2384, -0.3169, -0.9690, -0.1320]])

In [3]:
list(range(2, 3))

[2]

In [5]:
(3, ) + (1, 1)

(3, 1, 1)

In [6]:
[None] * 3

[None, None, None]

In [9]:
import numpy as np

t = np.array([[1, 2], [3, 4]])
t

array([[1, 2],
       [3, 4]])

In [8]:
len(t)

2

In [12]:
def add_one(x):
    x += 1

In [13]:
a = 4

add_one(a)

a

4

In [6]:
x = 8
if x:
    print(100)

100


In [7]:
if x >= 3 + 4:
    print("AKA")

AKA


In [12]:
import re

content = r'hellow python, 123, end.' 
pattern = 'hel'

result = re.match(pattern, content)
print(result)

<re.Match object; span=(0, 3), match='hel'>


In [26]:
print("ai\n")

ai



In [37]:
text = "linear(1,2,3)sdfkjsdk"

match = re.match(r'linear\((.+),(.+),.+\)', text)
print(match.groups())

('1', '2')
